version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: uhm
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X main.Version={{.Version}}
release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: uhm
    homepage: https://github.com/Thwani47/uhm
    repository:
      owner: Thwani47
      name: homebrew-tools
      branch: master
    commit_author:
      name: Thwani47
      email: thulaniinnocent47@gmail.com

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
