version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: uhm
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - flags:
      - -mod=vendor
release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: uhm
    homepage: https://github.com/Thwani47/uhm
    tap:
      owner: Thwan47
      name: homebrew-tools
    commit_author:
      name: Thwani47
      email: thulaniinnocent47@gmail.com
    branch: master

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
